# Generated by Django 5.1 on 2025-03-06 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliquotaSimples',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aliquota', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mes', models.CharField(blank=True, max_length=100, null=True)),
                ('ano', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anexos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('limite_superior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limite_inferior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deducao', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Criterios',
            fields=[
                ('id_aliquotas', models.AutoField(primary_key=True, serialize=False)),
                ('deducao_imposto', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_superior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limite_inferior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoDP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imposto', models.CharField(max_length=100)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_com_juros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('forma_envio', models.CharField(blank=True, max_length=100, null=True)),
                ('confirmacao', models.CharField(blank=True, max_length=100, null=True)),
                ('competencia', models.CharField(blank=True, max_length=100, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('despesa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('responsaveis', models.CharField(blank=True, max_length=100, null=True)),
                ('atividade', models.CharField(blank=True, max_length=100, null=True)),
                ('regime_apuracao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estadual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ie', models.CharField(blank=True, max_length=100, null=True)),
                ('login_estadual', models.CharField(blank=True, max_length=100, null=True)),
                ('senha_estadual', models.CharField(blank=True, max_length=100, null=True)),
                ('certificado_digital_estadual', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Federal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(blank=True, max_length=100, null=True)),
                ('login_federal', models.CharField(blank=True, max_length=100, null=True)),
                ('senha_federal', models.CharField(blank=True, max_length=100, null=True)),
                ('certificado_digital_federal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FonteReceita',
            fields=[
                ('id_fonte_receita', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True)),
                ('informacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ccm', models.CharField(blank=True, max_length=100, null=True)),
                ('login_municipal', models.CharField(blank=True, max_length=100, null=True)),
                ('senha_municipal', models.CharField(blank=True, max_length=100, null=True)),
                ('certificado_digital_municipal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ObrigacaoExtra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obrigacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_envio', models.DateField(blank=True, null=True)),
                ('data_limite', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='SimplesNacional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_anexo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id_transacoes', models.AutoField(primary_key=True, serialize=False)),
                ('transacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('fonte_receita', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vencimento',
            fields=[
                ('id_data_vencimento', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField(blank=True, null=True)),
                ('periodo_pagamento', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa_DP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_dp_dp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departamentodp')),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaAliquota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_aliquota_simples', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aliquotasimples')),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaDespesas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_despesa_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.despesas')),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='estadual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadual'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='federal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.federal'),
        ),
        migrations.CreateModel(
            name='EmpresaFonteReceita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('id_fonte_receita_fonte_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fontereceita')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('id_historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.historico')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='municipal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.municipal'),
        ),
        migrations.CreateModel(
            name='EmpresaObrigacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('id_obrigacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.obrigacaoextra')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaObservacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('id_observacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.observacoes')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
        ),
        migrations.CreateModel(
            name='SimplesAnexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.anexos')),
                ('id_simples', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.simplesnacional')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaSimples',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('id_simples', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.simplesnacional')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaTransacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('id_transacoes_transacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transacoes')),
            ],
        ),
        migrations.CreateModel(
            name='Tributo',
            fields=[
                ('id_tributo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('envio_email', models.DateField(blank=True, null=True)),
                ('confirmacao_email', models.DateField(blank=True, null=True)),
                ('aliquota', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regime', models.CharField(blank=True, max_length=100, null=True)),
                ('id_fonte_receita_fonte_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fontereceita')),
                ('id_data_vencimento_vencimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vencimento')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaTributo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('id_tributo_tributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tributo')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioAliquotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_aliquotas_criterios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.criterios')),
                ('id_tributo_tributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tributo')),
            ],
        ),
    ]
