# Generated by Django 5.1 on 2024-12-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexos',
            name='deducao',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
