# Generated by Django 5.1 on 2024-08-15 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterios',
            fields=[
                ('id_aliquotas', models.AutoField(primary_key=True, serialize=False)),
                ('deducao_imposto', models.IntegerField()),
                ('limite_superior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limite_inferior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Criterios',
            },
        ),
        migrations.CreateModel(
            name='Estadual',
            fields=[
                ('ie', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('certificado_digital', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'estadual',
            },
        ),
        migrations.CreateModel(
            name='Federal',
            fields=[
                ('cnpj', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('certificado_digital', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'federal',
            },
        ),
        migrations.CreateModel(
            name='Municipal',
            fields=[
                ('ccm', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('certificado_digital', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'municipal',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id_fonte_receita', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'receita',
            },
        ),
        migrations.CreateModel(
            name='Vencimento',
            fields=[
                ('id_data_vencimento', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('periodo_pagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vencimento',
            },
        ),
        migrations.CreateModel(
            name='Tributo',
            fields=[
                ('id_tributo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('id_aliquotas_Criterios', models.ForeignKey(db_column='id_aliquotas_Criterios', on_delete=django.db.models.deletion.CASCADE, to='app.criterios')),
                ('id_fonte_receita_receita', models.ForeignKey(db_column='id_fonte_receita_receita', on_delete=django.db.models.deletion.CASCADE, to='app.receita')),
                ('id_data_vencimento_vencimento', models.ForeignKey(db_column='id_data_vencimento_vencimento', on_delete=django.db.models.deletion.CASCADE, to='app.vencimento')),
            ],
            options={
                'db_table': 'tributo',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('responsaveis', models.CharField(blank=True, max_length=100, null=True)),
                ('atividade', models.CharField(blank=True, max_length=100, null=True)),
                ('ie_estadual', models.ForeignKey(db_column='ie_estadual', on_delete=django.db.models.deletion.CASCADE, to='app.estadual')),
                ('cnpj_federal', models.ForeignKey(db_column='cnpj_federal', on_delete=django.db.models.deletion.CASCADE, to='app.federal')),
                ('ccm_municipal', models.ForeignKey(db_column='ccm_municipal', on_delete=django.db.models.deletion.CASCADE, to='app.municipal')),
                ('id_tributo_tributo', models.ForeignKey(db_column='id_tributo_tributo', on_delete=django.db.models.deletion.CASCADE, to='app.tributo')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
    ]
