# Generated by Django 5.1 on 2025-01-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_anexos_deducao'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentodp',
            name='competencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='departamentodp',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
