# Generated by Django 5.1 on 2024-08-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_criterios_estadual_federal_municipal_receita_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadual',
            old_name='certificado_digital',
            new_name='certificado_digital_estadual',
        ),
        migrations.RenameField(
            model_name='estadual',
            old_name='login',
            new_name='login_estadual',
        ),
        migrations.RenameField(
            model_name='estadual',
            old_name='senha',
            new_name='senha_estadual',
        ),
        migrations.RenameField(
            model_name='federal',
            old_name='certificado_digital',
            new_name='certificado_digital_federal',
        ),
        migrations.RenameField(
            model_name='federal',
            old_name='login',
            new_name='login_federal',
        ),
        migrations.RenameField(
            model_name='federal',
            old_name='senha',
            new_name='senha_federal',
        ),
        migrations.RenameField(
            model_name='municipal',
            old_name='certificado_digital',
            new_name='certificado_digital_municipal',
        ),
        migrations.RenameField(
            model_name='municipal',
            old_name='login',
            new_name='login_municipal',
        ),
        migrations.RenameField(
            model_name='municipal',
            old_name='senha',
            new_name='senha_municipal',
        ),
        migrations.AddField(
            model_name='empresa',
            name='regime_apuracao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estadual',
            name='ie',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='federal',
            name='cnpj',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='municipal',
            name='ccm',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vencimento',
            name='dia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vencimento',
            name='mes',
            field=models.DateField(blank=True, null=True),
        ),
    ]
