# Generated by Django 5.1 on 2025-01-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_departamentodp_competencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrigacaoExtra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obrigacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_envio', models.DateField(blank=True, null=True)),
                ('data_limite', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='empresadespesas',
            name='id_despesa_despesa',
        ),
        migrations.AddField(
            model_name='empresadespesas',
            name='id_obrigacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.obrigacaoextra'),
            preserve_default=False,
        ),
    ]
