# Generated by Django 5.1 on 2024-08-16 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_certificado_digital_estadual_certificado_digital_estadual_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empresa',
            table=None,
        ),
        migrations.AlterModelTable(
            name='estadual',
            table=None,
        ),
        migrations.AlterModelTable(
            name='federal',
            table=None,
        ),
        migrations.AlterModelTable(
            name='municipal',
            table=None,
        ),
        migrations.AlterModelTable(
            name='receita',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tributo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vencimento',
            table=None,
        ),
    ]
