# Generated by Django 5.1 on 2024-08-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_empresa_table_alter_estadual_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterios',
            name='deducao_imposto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
