# Generated by Django 5.1 on 2024-08-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_criterios_deducao_imposto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='criterios',
            table=None,
        ),
    ]
