# Generated by Django 5.1 on 2025-02-04 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_empresadespesas_id_obrigacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliquotaSimples',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aliquota', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mes', models.CharField(blank=True, max_length=100, null=True)),
                ('ano', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaAliquota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_aliquota_simples', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aliquotasimples')),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
    ]
