# Generated by Django 5.1 on 2024-11-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tributo_confirmacao_email_tributo_envio_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoDP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imposto', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=5, max_digits=10)),
                ('valor_com_juros', models.DecimalField(decimal_places=5, max_digits=10)),
                ('local_pagamento', models.CharField(max_length=100)),
                ('data_pagamento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa_DP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_dp_dp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departamentodp')),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
    ]
