# Generated by Django 5.1 on 2024-11-15 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_departamentodp_empresa_dp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('despesa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='departamentodp',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departamentodp',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='departamentodp',
            name='valor_com_juros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='EmpresaDespesas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_despesa_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.despesas')),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
    ]
