# Generated by Django 5.1 on 2024-11-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_anexos_simplesnacional_simplesanexo_empresasimples'),
    ]

    operations = [
        migrations.AddField(
            model_name='tributo',
            name='aliquota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tributo',
            name='regime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
