# Generated by Django 5.1 on 2024-11-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_tributo_aliquota_tributo_regime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentodp',
            name='local_pagamento',
        ),
        migrations.AddField(
            model_name='departamentodp',
            name='confirmacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='departamentodp',
            name='forma_envio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
